### ISSUE TITLE
Can this add-on running on openHAB2?

### ISSUE THREAD

**Issue by SchumyHao** [octa22/org.openhab.binding.xiaomigateway#1]
Hi 
This is a great work.
But can this work on openHAB2?

**Comment by octa22** [comment]
Please test this binding https://github.com/carecon/openhab2-addons/tree/master/addons/binding/org.openhab.binding.mihome

it is based on some portions of my code and is written for OH2 since the very begining

**Comment by SchumyHao** [comment]
thanks a lot
