### ISSUE TITLE
Unable to add things

### ISSUE THREAD

**Issue by famaia** [octa22/org.openhab.binding.xiaomigateway#3]
I get an empty white web page when trying to add a thing.

Logs say: Exception in thread "XiaomiGateway Refresh Service" java.lang.IllegalArgumentException: timeout value is negative

Any clues?

**Comment by octa22** [comment]
Sorry - since this is an OH1 binding I can't assist you with OH2 things. You can use this binding in OH2 but you have to use it OH1 way by defining items and sitemaps, no things.
