### ISSUE TITLE
motion sensor?

### ISSUE THREAD

**Issue by farhanito** [octa22/org.openhab.binding.xiaomigateway#5]
hi, 
how to configure a motion sensor?

the sensor is detected fine
`[INFO ] [ateway.internal.XiaomiGatewayBinding] - Detected Xiaomi smart device - sid: 158d0001144b47 model: motion`

tried creating an item like
`Switch XiaomiMotion "Motion" <motion> {xiaomigateway="158d0001144b47.motion"}`

but i got error
`[ERROR] [ateway.internal.XiaomiGatewayBinding] - java.lang.NullPointerException`

thanks,
farhan

**Comment by octa22** [comment]
Hello,
I'm sorry it doesn't work - i don't have a motion sensor so for me it's not easy to investigate the motion behaviour. 
Which version have you tried? Can you please send me more of the log file so I can see gateway initialization and packets received?
Thanks

**Comment by farhanito** [comment]
Hi,

My bad. Changed the item type to Contact, and it works perfectly. 
Sorry about that :).

Thanks

**Comment by octa22** [comment]
Nevermind - I've added to documentation example of motion sensor binding config. Hope it helps...
