### ISSUE TITLE
xiaomi zigbee plug? 

### ISSUE THREAD

**Issue by farhanito** [octa22/org.openhab.binding.xiaomigateway#7]
hi, 

just received couple of xiaomi zigbee plug. does your binding support it? 

thanks

**Comment by farhanito** [comment]
UPDATE:

it does detected by the binding. 

> 2017-03-11 09:15:14.058 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"read_ack","model":"plug","sid":"158d00013e52d1","short_id":4797,"data":"{\"status\":\"off\",\"inuse\":\"0\"}"} 2017-03-11 09:15:14.062 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Detected Xiaomi smart device - sid: 158d00013e52d1 model: plug

> 09:17:43.566 [INFO ] [ateway.internal.XiaomiGatewayBinding] - Xiaomi received packet: {"cmd":"heartbeat","model":"plug","sid":"158d00013e52d1","short_id":4797,"data":"{\"status\":\"off\",\"inuse\":\"0\"}"}

will do some test later

**Comment by octa22** [comment]
hi, I have just obtained a zigbee plug today, support added to 1.10-SNAPSHOT. I'll release it asap.

**Comment by farhanito** [comment]
Thanks, works with the new version. 
Any chance to get the power consumption report?

**Comment by octa22** [comment]
Unfortunately power consumption report is mentioned in API docs but not published by the gateway. Hopefully some new FW update will add the support and I'll add the power consupmtion support too

**Comment by farhanito** [comment]
understand, thank you. 

oh, one more thing... 
i don't really understand the virtual_switch item. which device (sid) related to it? the button? 
i see from the example, the virtual_switch sid is different from click/longclick/doubleclick item. 

Thanks

**Comment by octa22** [comment]
Virtual switch is a button which remembers its state so his functionality is the same as a ON/OFF button (maybe toggle event is better). I'm using it as a ventilator switch in my bathroom. I have more buttons in my home, I'll update the documentation to be more clear it relates to previously mentioned button. thanks

**Comment by farhanito** [comment]
there is a new firmware update for the gateway. hopefully this will bring the power consumption report.

**Comment by octa22** [comment]
You are right, the voltage is being reported since this FW update, I'll add support during this weekend

**Comment by octa22** [comment]
{\"voltage\":3600,\"status\":\"on\",\"inuse\":\"1\",\"power_consumed\":\"16\",\"load_power\":\"1\"}"}

**Comment by farhanito** [comment]
excellent

**Comment by octa22** [comment]
Support added in https://github.com/octa22/org.openhab.binding.xiaomigateway/commit/b74b9f2d797e7678cb3a2dceb9f895f5189c7409
