### ISSUE TITLE
Plug status change delayed

### ISSUE THREAD

**Issue by schmieeed** [octa22/org.openhab.binding.xiaomigateway#8]
The plug item works fine if the inuse status changed from ON to OFF (change will be recognised immediately). But if the inuse status changed from OFF to ON it needs up to 5 minutes to recognise the change on the item :-(

**Comment by octa22** [comment]
This is not a bug but a feature. The gateway sends the inuse event state after a couple of minutes. There's a workaround for the OFF event - when OFF status is received, OFF for inuse is automatically published. But this can't be applied to ON status event (plug ON doesn't implicate ON for inuse)

**Comment by octa22** [comment]
The bahaviour is improved in https://github.com/octa22/org.openhab.binding.xiaomigateway/releases/tag/1.10.0-SNAPSHOT2
the plug changes (other sensors too) are polled every refresh interval so you can control how fast are some changes recognised
